# Generated by Django 2.2.1 on 2019-08-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_title', models.CharField(max_length=100)),
                ('trip_subtitle', models.CharField(max_length=100)),
                ('cover', models.TextField()),
                ('pub_time', models.DateTimeField(verbose_name='date published')),
                ('place', models.CharField(max_length=100)),
                ('likeCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_title', models.CharField(max_length=100)),
                ('trip_subtitle', models.CharField(max_length=100)),
                ('trip_day', models.IntegerField(default=1)),
                ('cover', models.TextField()),
                ('pub_time', models.DateTimeField(verbose_name='date published')),
                ('place', models.CharField(max_length=100)),
                ('likeCount', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trip')),
            ],
        ),
    ]
